<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carte [
    <!--- Carte de visite -->
    <!ELEMENT carte (logo,prenom,nom,fonction,email,telmobile,societe,devise,siteweb)>
    
    <!--- Logo de la société -->
    <!ELEMENT logo EMPTY>
    <!ATTLIST logo src ENTITY #REQUIRED>
    <!ENTITY logo SYSTEM "./logo.jpeg" NDATA jpeg>
    <!NOTATION jpeg SYSTEM "paint.exe">
    
    <!--- Prénom du contact -->
    <!ELEMENT prenom (#PCDATA)>
    
    <!--- Nom du contact -->
    <!ELEMENT nom (#PCDATA)>
    
    <!--- Fonction dans la société -->
    <!ELEMENT fonction (#PCDATA)>
    
    <!--- Adresse email du contact -->
    <!ELEMENT email (#PCDATA)>
    
    <!--- Numéro de téléphone du contact -->
    <!ELEMENT telmobile (#PCDATA)>

    <!--- Société du contact -->
    <!ELEMENT societe (#PCDATA)>

    <!--- Devise de la société -->
    <!ELEMENT devise (#PCDATA)>
    
    <!--- Site web de la société -->
    <!ELEMENT siteweb (#PCDATA)> 
]>
<?xml-stylesheet type="text/css" href="business_card.css" ?>

<!--
    Document   : carte_visite.xml
    Created on : 19 février 2007, 11:57
    Author     : Jérémie DECOCK
    Description: Carte de visite de Jérémie DECOCK.
-->

<carte>
    <logo src="logo" />
    <prenom>jérémie</prenom>
    <nom>decock</nom>
    <fonction>Project Manager</fonction>
    <email>jeremie.decock@metis-live.org</email>
    <telmobile>+33 6 01 02 03 04</telmobile>
    <societe>metis live</societe>
    <devise>Freedom is a choice</devise>
    <siteweb>www.metis-live.org</siteweb>
</carte>
