=== asadana/snippets/sax_java/hello_sax/library.dtd
<!ELEMENT library (book*)>
<!ELEMENT book (title,author+,tag*)>
<!ATTLIST book date CDATA #REQUIRED
               isbn CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT tag (#PCDATA)>

=== asadana/snippets/java/sax/hello_sax/test_ns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd" >

<library xmlns="http://www.jdhp.org/ns/library">
	<book date="1998-03-01" isbn="0262193981">
		<title><![CDATA[Reinforcement Learning: An Introduction]]></title>
		<author>Richard S. Sutton</author>
		<author>Andrew G. Barto</author>
        <tag>Computer Science</tag>
        <tag>Artificial Intelligence</tag>
        <tag>Reinforcement Learning</tag>
    </book>
	<book date="2009-12-11" isbn="0136042594">
		<title><![CDATA[Artificial Intelligence: A Modern Approach]]></title>
		<author>Stuart Russell</author>
		<author>Peter Norvig</author>
        <tag>Computer Science</tag>
        <tag>Artificial Intelligence</tag>
    </book>
</library>

=== asadana/snippets/sax_java/hello_sax/test_not_valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd" >

<library>
	<book date="foo" isbn="foo">
		<author>Richard S. Sutton</author>
		<author>Andrew G. Barto</author>
        <tag>Computer Science</tag>
        <tag>Artificial Intelligence</tag>
        <tag>Reinforcement Learning</tag>
    </book>
	<foo date="2009-12-11" isbn="0136042594">
		<title><![CDATA[Artificial Intelligence: A Modern Approach]]></title>
		<author>Stuart Russell</author>
		<author>Peter Norvig</author>
        <tag>Computer Science</tag>
        <tag>Artificial Intelligence</tag>
    </foo>
</library>
